### PR TITLE
Recognize error from deletion on '::outside'

### PR DESCRIPTION
**Pull request by tomjw64**
Handles issue #90. Easybake will now recognize the strange behavior rather than erroring and exiting from what is technically valid input.

**Copied from my explanation on the issue.**

> A short example of what causes failure:
> This markup
> ```html
> <html>
>   <div class="select-me">
>     <span>Text</span>
>   </div>
> </html>
> ```
> baked with
> ```css
> .select-me::outside { content: pending(empty-bucket); }
> .select-me::outside { content: content(); }
> ```
> yields the same error. After the first `::outside`, `.select-me` is removed from its parent because its content was set to an empty group. On the second `::outside`, `.select-me`'s parent is found, but it no longer has `.select-me` as a descendant, causing an IndexError. The change in PR #91 catches and warns about this behavior.

### CODE REVIEW

**Comment by reedstrm** [comment]
So, what is the expected result for this? BTW, ::outside w/ an empty bucket is an interesting trick for deleting …

**Comment by reedstrm** [comment]
Tagged this to 10-8 release, to get passed the business-book release, hopefully.

**Comment by reedstrm** [comment]
This will now error, but not throw a traceback.

**Comment by reedstrm** [comment]
@tomjw64 This has been approved months ago, and held back for a big press of book releases. Van it get merged now?

**Comment by tomjw64** [comment]
@reedstrm Should be good to go!

**Comment by brittweinstein** [comment]
@tomjw64 how should this be tested?

**Comment by tomjw64** [comment]
@brittweinstein We don't have any instances of this happening in our recipes, otherwise they would be broken. In my opinion it's likely sufficient the unit tests passed on cnx-easybake. If we really wanted to test this though, we would have to run easybake on every single book in our library before and after this change and ensure that no changes occurred.

**Pull request merged**
